#include "Vhello_world.h" // Generated by Verilator
#include "verilated.h"

int main(int argc, char **argv)
{
    Verilated::commandArgs(argc, argv);
    Vhello_world *top = new Vhello_world;

    int ticks = 0;
    while (ticks < 5)
    { // Run for 5 clock cycles
        top->clk = 0;
        top->eval();
        top->clk = 1;
        top->eval();
        ticks++;
    }

    delete top;
    return 0;
}